### ISSUE TITLE
Ubuntu 17.10 - Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'

### ISSUE THREAD

**Issue by ariesmartin** [yomun/youdaodict_5.5#3]
已安装Nvidia 启动 和所有依赖
有道也成功安装 但是无法打开 没有反应

**Comment by yomun** [comment]
Ubuntu 17.10 预设用 Wayland 为显示服务器, 
但 Nvidia 对 Wayland 支持不太好, 所以改用 xOrg

安装 nvidia-396 后 (目前最新版本), 在 
$ sudo gedit /etc/gdm3/custom.conf
将 # WaylandEnable=false 前面的 # 拿走, 储存, 重启..

**Comment by yomun** [comment]
另外,
在 terminal 运行 youdao-dict (非 root 账号) 看看有没有显示什么错误

**Comment by ariesmartin** [comment]
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in <module>
    from dae.window import Window
  File "/usr/share/youdao-dict/dae/window.py", line 30, in <module>
    from dae.shadowwindow import ShadowWindow
  File "/usr/share/youdao-dict/dae/shadowwindow.py", line 28, in <module>
    import dae.xutils as xutils
  File "/usr/share/youdao-dict/dae/xutils.py", line 25, in <module>
    ewmh = EWMH()
  File "/usr/share/youdao-dict/dae/ewmh.py", line 50, in __init__
    self.display = _display or display.Display()
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'

改了以后还是无法打开窗口

**Comment by yomun** [comment]
在 terminal 加上
$ xhost + && youdao-dict

我有在 README.md 上提到, 这是 python-xlib 引起的 bugs
解决方法早就给了

**Comment by ariesmartin** [comment]
可以运行了 感谢!
