### ISSUE TITLE
Ubuntu 18.04 - ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by Kcaii** [yomun/youdaodict_5.5#4]
When I run `youdao-dict` in terminal, the following message appears:
```
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in <module>
    from dae.window import Window
  File "/usr/share/youdao-dict/dae/window.py", line 29, in <module>
    from dae.webview import WebView
  File "/usr/share/youdao-dict/dae/webview.py", line 27, in <module>
    from dae.webpage import WebPage
  File "/usr/share/youdao-dict/dae/webpage.py", line 27, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```
My Runtime Enviroment:

* OS: Ubuntu 18.04 LTS x86_64
* Kernel: 4.15.0-20-generic
* Shell: bash 4.4.19
* DE: GNOME 3.28.1
* GPU: NVIDIA GeForce GTX 1060 Mobile

**Comment by Kcaii** [comment]
I found an answer on [StackOverflow](https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5). The `PyQt5.QtWebKitWidgets` had been deprecated. And `PyQt5.QtWebEngineWidgets` takes the place of it. Maybe the solution is **to refactor the code** or **downgrade PyQt5 to an older version**.

**Comment by yomun** [comment]
你用的有道词典不是我提供的 1.1.1 版本

- 1.1.0 最高支持到 PyQt 5.5 (Ubuntu 16.04 以后的版本就不能用了)
- 1.1.1 能支持 PyQt 5.5 或更高 (目前已在 Ubuntu 16.04 - 18.04 测试过了)

所以根本不会出现你说的问题, 除非你用 1.1.1 以外的版本

- Ubuntu 18.04 提供的是 PyQt 5.10.1, 所以必须安装 1.1.1
- 至于所需依赖软件包已在 README.md 全列出, 请确保都安装了

**Comment by Kcaii** [comment]
我用的是是您提供的 1.1.1版本。
用 `dpkg` 查询得到以下信息：
`ii  youdao-dict    1.1.1-0~ubun amd64        Youdao Dict for Linux`

以防万一，我`purge`之后重新下载安装了一遍，结果还是出错。

`pip list`查询得到`PyQt5`版本信息是：`PyQt5 (5.10.1)`

***

用`terminal` 测试了一下`python`。Python2 导入模块成功
```
$ python2
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
>>> PyQt5
<module 'PyQt5' from '/usr/lib/python2.7/dist-packages/PyQt5/__init__.pyc'>
```

***

Python3导入模块失败
```
$ Python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
>>> PyQt5
<module 'PyQt5' from '/home/username/.local/lib/python3.6/site-packages/PyQt5/__init__.py'>
```

***

不知道是哪里出了问题，前段时间用得好好的，最近又不能用了。

**Comment by yomun** [comment]
你用 pip3 安装 PyQt5 (5.10.1) 已破坏原有的配置了
现在的解决方法是重安装 Ubuntu, 一切重头开始.
以后, 记得不要用 pip3 安装 PyQt5.

**Comment by Kcaii** [comment]
没那么严重……
问题已经解决了。
`pip uninstall pyqt5 && pip3 uninstall pyqt5`卸载 `PyQt 5.10.1`，之后成功运行有道。

再检查`PyQt5`版本
```bash
$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> PyQt5.QtCore.qVersion()
'5.9.5'
```
看来 `PyQt 5.9.5`还是好的， `PyQt 5.10.1`会出现问题。

解决方案还是我之前说的那个：
> I found an answer in StackOverflow. The PyQt5.QtWebKitWidgets had been deprecated. And PyQt5.QtWebEngineWidgets takes the place of it. Maybe the solution is to refactor the code or downgrade PyQt5 to an older version.

**Comment by yomun** [comment]
测试环境: VirtualBox 5.2.10 上安装的 Ubuntu 18.04 正式版

0) 如 README.md 所说安装有道词典.

1) 用 pip3 安装 PyQt5 (非 root 户口)
```
$ su
$ apt install python3-pip

$ pip3 install pyqt5

打开另一个终端输入..
$ su
$ pip3 list | grep PyQt5       # 也会显示 PyQt5 (5.10.1)
```
2) pip3 安装 PyQt5 后, 运行 youdao-dict 出现错误
```
$ youdao-dict
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in <module>
    from dae.window import Window
  File "/usr/share/youdao-dict/dae/window.py", line 29, in <module>
    from dae.webview import WebView
  File "/usr/share/youdao-dict/dae/webview.py", line 27, in <module>
    from dae.webpage import WebPage
  File "/usr/share/youdao-dict/dae/webpage.py", line 27, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

$ python3
>>> from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

问题如你所提的一样..

推断:
- Ubuntu 将这模块分出(但可选择安装), 而 pip3 的安装包不包括这不再发展的模块(PyQt 5.6 开始)
apt 安装位置: /usr/lib/python3/dist-packages/PyQt5
pip3 安装位置: 
/usr/local/lib/python3.6/site-packages/PyQt5
~/.local/lib/python3.6/site-packages/PyQt5
比较下, 明显 pip3 安装位置里少了以上模块
```
3) pip3 卸载 PyQt5
```
$ su
$ pip3 uninstall PyQt5

打开另一个终端输入..
$ su
$ pip3 list | grep PyQt5        # PyQt5 (5.10.1) 显示没有了
```
4.1) pip3 卸载 PyQt5 成功, 再运行 youdao-dict, 错误没有了, 成功运行
测试环境: VirtualBox 5.2.10 上安装的 Ubuntu 18.04 正式版

- 从头到尾, 不需卸载 apt 已安装的软件包 (包含 PyQt5) 和有道词典, 也不需要降级
- 有道词典是 python3 程序, 所以即便 
pip 安装了 PyQt5 也不受影响, 因这 PyQt5 不给 python 3 用, 而是给 Python 2  
(我连 python-pip 也没安装, 完全没用 pip)

4.2) pip3 卸载 PyQt5 无效, 而且出现 Segmentation fault (也是同一行引起的错误)
测试环境: wubi 安装的 Ubuntu 17.10
```
$ youdao-dict
Segmentation fault

$ python3
>>> from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
Segmentation fault

$ su
$ pip3 uninstall PyQt5

$ youdao-dict
```

**Comment by Kcaii** [comment]
刚刚又测试了一下，找到了问题所在。

@yomun 你的推断是对的
> 推断:
> - Ubuntu 将这模块分出(但可选择安装), 而 pip3 的安装包不包括这不再发展的模块(PyQt 5.6 开始)

* `apt-get` 安装的 `PyQt5`

  用`dpkg`查询包结果如下：
  ```
  ~$ dpkg -l | grep pyqt5

  ii  python-pyqt5.qtwebkit                         5.10.1+dfsg-1ubuntu2                amd64        Python 2 bindings for Qt5's WebKit module

  ii  python3-pyqt5.qtwebkit                        5.10.1+dfsg-1ubuntu2                amd64        Python 3 bindings for Qt5's WebKit module
  ```

  查询这两个包的内容，结果如下：

  ```
  ~$ dpkg -L python3-pyqt5.qtwebkit
  /.
  /usr
  /usr/lib
  /usr/lib/python3
  /usr/lib/python3/dist-packages
  /usr/lib/python3/dist-packages/PyQt5
  /usr/lib/python3/dist-packages/PyQt5/QtWebKit.cpython-36m-x86_64-linux-gnu.so
  /usr/lib/python3/dist-packages/PyQt5/QtWebKit.pyi
  /usr/lib/python3/dist-packages/PyQt5/QtWebKitWidgets.cpython-36m-x86_64-linux-gnu.so
  /usr/lib/python3/dist-packages/PyQt5/QtWebKitWidgets.pyi
  /usr/share
  /usr/share/doc
  /usr/share/doc/python3-pyqt5.qtwebkit
  /usr/share/doc/python3-pyqt5.qtwebkit/copyright
  /usr/share/doc/python3-pyqt5.qtwebkit/changelog.Debian.gz

  ~$ dpkg -L python-pyqt5.qtwebkit
  /.
  /usr
  /usr/lib
  /usr/lib/python2.7
  /usr/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages/PyQt5
  /usr/lib/python2.7/dist-packages/PyQt5/QtWebKit.x86_64-linux-gnu.so
  /usr/lib/python2.7/dist-packages/PyQt5/QtWebKitWidgets.x86_64-linux-gnu.so
  /usr/share
  /usr/share/doc
  /usr/share/doc/python-pyqt5.qtwebkit
  /usr/share/doc/python-pyqt5.qtwebkit/copyright
  /usr/share/doc/python-pyqt5.qtwebkit/changelog.Debian.gz
  ```

  这两个包是就是所谓的"选择安装"模块，包中包含`QtWebKitWidgets`模块。安装路径分别为：`/usr/lib/python2.7/dist-packages/PyQt5`和`/usr/lib/python3/dist-packages/PyQt5`。所以`youdao-dict`能正常运行。

* `pip` 安装的 `PyQt5`

  `~/.config/pip/pip.conf`内容如下：
  ```
  [global]
  timeout = 10
  index-url = https://pypi.tuna.tsinghua.edu.cn/simple
  target = /usr/local/lib/python3.6/dist-packages
  ```
  ```
  ~$ sudo pip3 install PyQt5
  ...
  Successfully installed PyQt5-5.10.1 sip-4.19.8
  Target directory /usr/local/lib/python3.6/dist-packages/
  ...

  ~$ sudo pip install PyQt5
  ...
  Successfully installed PyQt5-5.10.1 sip-4.19.8
  Target directory /usr/local/lib/python3.6/dist-packages/
  ...
  ```

  `pip`和`pip3`的安装路径都是`/usr/local/lib/python3.6/dist-packages`

    查看这个目录下的`PyQt5`文件夹：
  ```
  ~$ ls /usr/local/lib/python3.6/dist-packages/PyQt5
  __init__.py                    QtHelp.so               Qt.so
  __pycache__                    QtLocation.so           QtSql.so
  pylupdate_main.py              QtMultimedia.so         QtSvg.so
  pylupdate.so                   QtMultimediaWidgets.so  QtTest.so
  pyrcc_main.py                  QtNetworkAuth.so        QtWebChannel.so
  pyrcc.so                       QtNetwork.so            QtWebEngineCore.so
  _QOpenGLFunctions_2_0.so       QtNfc.so                QtWebEngine.so
  _QOpenGLFunctions_2_1.so       QtOpenGL.so             QtWebEngineWidgets.so
  _QOpenGLFunctions_4_1_Core.so  QtPositioning.so        QtWebSockets.so
  Qt                             QtPrintSupport.so       QtWidgets.so
  QtBluetooth.so                 QtQml.so                QtX11Extras.so
  QtCore.so                      QtQuick.so              QtXmlPatterns.so
  QtDBus.so                      QtQuickWidgets.so       QtXml.so
  QtDesigner.so                  QtSensors.so            uic
  QtGui.so                       QtSerialPort.so
  ```
  其中并不包含`QtWebKitWidgets`，只有`QtWebEngine`，所以`youdao-dict`运行出错。

* `pip`和`apt-get`安装的`PyQt5`并存

  我没有设置`PYTHONHOME`环境变量，使用的是默认的`sys.path`

  ```
  ~$ python3
  Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
  [GCC 7.3.0] on linux
  Type "help", "copyright", "credits" or "license" for more information.

  >>> import sys
  >>> sys.path
  ['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/mark/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
  ```

  查了一下 [官方文档](https://docs.python.org/3/library/sys.html#sys.path)：
  > sys.path
  > A list of strings that specifies the search path for modules. Initialized from the environment variable PYTHONPATH, plus an installation-dependent default.
  >
  > As initialized upon program startup, the first item of this list, path[0], is the directory containing the script that was used to invoke the Python interpreter. If the script directory is not available (e.g. if the interpreter is invoked interactively or if the script is read from standard input), path[0] is the empty string, which directs Python to search modules in the current directory first. Notice that the script directory is inserted before the entries inserted as a result of PYTHONPATH.

  模块`import`的策略是逐个查找`sys.path`中的目录，直到找到第一个相符的模块。

  在`pip | pip3 install PyQt5`之前，这个目录是`/usr/lib/python3/dist-packages`，其中有`python3-pyqt5.qtwebkit`可选包的`QtWebKitWidgets`，所以`youdao-dict`能够正确运行。

  但是安装之后，因为`/usr/local/lib/python3.6/dist-packages`在`sys.path`中排在`/usr/lib/python3/dist-packages`之前，所以`youdao-dict`使用的是`/usr/local/lib/python3.6/dist-packages`中的`PyQt5`模块，即不包含`QtWebKitWidgets`模块，`youdao-dict`运行出错。

由此看来，**不能使用`pip`安装`PyQt5`**，应**使用`apt-get`安装**。并且一定要一同安装`python3-pyqt5.qtwebkit`这个包。

> 可选：重构代码，把`QtWebKitWidgets`换成`QtWebEngine`。
>            安装以前的包含`QtWebKitWidgets`的`PyQt5`。

> 另：我之所以用`pip`，是因为我用`Pycharm`码代码以及管理Python模块，它会默认安装pip。为了避免出现bug，我用`terminal`和`pip`同时安装了`PyQt5`，没想到还是出了问题......

**Comment by Sophia409** [comment]
@Kcaii 您好，我也遇到了和您一样的问题，但是我的pip list 里面没有pyqt5，并且根据readme用apt安装的。我看到了您发的那个stackoverflow帖子，但是由于我是新手，实在还是解决不了。
The PyQt5.QtWebKitWidgets had been deprecated. And PyQt5.QtWebEngineWidgets takes the place of it. Maybe the solution is to refactor the code or downgrade PyQt5 to an older version.我不知道如何更改有道的code，也不知道如何用正确的方式将PyQt5还原到旧版本。希望得到您的帮助！
```
yuhong@zyh:~/snap/firefox/common/Downloads$ ls
Anaconda3-2018.12-Linux-x86_64.sh  mmc3.xlsx
l1_thalamus.loom                   youdao-dict_1.1.1-0~ubuntu_amd64.deb
yuhong@zyh:~/snap/firefox/common/Downloads$ pip3 list | grep PyQt5
Command 'pip3' not found, but can be installed with:
sudo apt install python3-pip
yuhong@zyh:~/snap/firefox/common/Downloads$ pip list | grep pyth
ipython                            7.2.0     
ipython-genutils                   0.2.0     
python-dateutil                    2.7.5     


yuhong@zyh:~/snap/firefox/common/Downloads$ sudo dpkg -i youdao-dict_1.1.1-0~ubuntu_amd64.deb
(正在读取数据库 ... 系统当前共安装有 201817 个文件和目录。)
正准备解包 youdao-dict_1.1.1-0~ubuntu_amd64.deb  ...
正在将 youdao-dict (1.1.1-0~ubuntu) 解包到 (1.1.1-0~ubuntu) 上 ...
正在设置 youdao-dict (1.1.1-0~ubuntu) ...
正在处理用于 bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) 的触发器 ...
Rebuilding /usr/share/applications/bamf-2.index...
正在处理用于 gnome-menus (3.13.3-11ubuntu1.1) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1ubuntu3.18.04.2) 的触发器 ...
正在处理用于 mime-support (3.60ubuntu1) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...

yuhong@zyh:~/snap/firefox/common/Downloads$ youdao-dict
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in <module>
    from dae.window import Window
  File "/usr/share/youdao-dict/dae/window.py", line 29, in <module>
    from dae.webview import WebView
  File "/usr/share/youdao-dict/dae/webview.py", line 27, in <module>
    from dae.webpage import WebPage
  File "/usr/share/youdao-dict/dae/webpage.py", line 27, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

yuhong@zyh:~/snap/firefox/common/Downloads$ dpkg -l | grep pyqt5
ii  python3-pyqt5                              5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5
ii  python3-pyqt5-dbg                          5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5 (debug extensions)
ii  python3-pyqt5.qtmultimedia                 5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5's Multimedia module
ii  python3-pyqt5.qtquick                      5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for QtQuick module
ii  python3-pyqt5.qtwebkit                     5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5's WebKit module

yuhong@zyh:~/snap/firefox/common/Downloads$ dpkg -L python3-pyqt5.qtwebkit
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/PyQt5
/usr/lib/python3/dist-packages/PyQt5/QtWebKit.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/PyQt5/QtWebKit.pyi
/usr/lib/python3/dist-packages/PyQt5/QtWebKitWidgets.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/PyQt5/QtWebKitWidgets.pyi
/usr/share
/usr/share/doc
/usr/share/doc/python3-pyqt5.qtwebkit
/usr/share/doc/python3-pyqt5.qtwebkit/copyright
/usr/share/doc/python3-pyqt5.qtwebkit/changelog.Debian.gz
```

**Comment by GDCenter** [comment]
@yomun 请问哪里去下载1.1.1版本,官网上是1.1.0版本的下载地址啊

**Comment by yomun** [comment]
https://github.com/yomun/youdaodict_5.5
不会吧, 发帖前连主页 README 也不看?
还是 '不小心' 弄错, 去了分支, 主分支当看不到?

**Comment by liuxiaohui1221** [comment]
ubuntu20版本也出现这个怎么弄啊
