### ISSUE TITLE
Ubuntu 18.04 - ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets

### ISSUE THREAD

**Issue by Sophia409** [yomun/youdaodict_5.5#8]
@yomun 
您好，我一步一步按照您的README.md完成了整个安装过程，我的pip list 里面没有PyQt5。但是不知道为什么一直提示No module named 'PyQt5.QtWebKitWidgets'。
之前的帖子提示：The PyQt5.QtWebKitWidgets had been deprecated. And PyQt5.QtWebEngineWidgets takes the place of it. Maybe the solution is to refactor the code or downgrade PyQt5 to an older version.但我不知道如何更改有道的code，也不知道如何用正确的方式将PyQt5还原到旧版本。希望得到您的帮助！
```
yuhong@zyh:~/snap/firefox/common/Downloads$ ls
Anaconda3-2018.12-Linux-x86_64.sh  mmc3.xlsx
l1_thalamus.loom                   youdao-dict_1.1.1-0~ubuntu_amd64.deb
yuhong@zyh:~/snap/firefox/common/Downloads$ pip3 list | grep PyQt5

Command 'pip3' not found, but can be installed with:

sudo apt install python3-pip
yuhong@zyh:~/snap/firefox/common/Downloads$ pip list | grep pyth
ipython                            7.2.0     
ipython-genutils                   0.2.0     
python-dateutil                    2.7.5     


yuhong@zyh:~/snap/firefox/common/Downloads$ sudo dpkg -i youdao-dict_1.1.1-0~ubuntu_amd64.deb
(正在读取数据库 ... 系统当前共安装有 201817 个文件和目录。)
正准备解包 youdao-dict_1.1.1-0~ubuntu_amd64.deb  ...
正在将 youdao-dict (1.1.1-0~ubuntu) 解包到 (1.1.1-0~ubuntu) 上 ...
正在设置 youdao-dict (1.1.1-0~ubuntu) ...
正在处理用于 bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) 的触发器 ...
Rebuilding /usr/share/applications/bamf-2.index...
正在处理用于 gnome-menus (3.13.3-11ubuntu1.1) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1ubuntu3.18.04.2) 的触发器 ...
正在处理用于 mime-support (3.60ubuntu1) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...

yuhong@zyh:~/snap/firefox/common/Downloads$ youdao-dict
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in <module>
    from dae.window import Window
  File "/usr/share/youdao-dict/dae/window.py", line 29, in <module>
    from dae.webview import WebView
  File "/usr/share/youdao-dict/dae/webview.py", line 27, in <module>
    from dae.webpage import WebPage
  File "/usr/share/youdao-dict/dae/webpage.py", line 27, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage, QWebInspector
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```
```
yuhong@zyh:~/snap/firefox/common/Downloads$ dpkg -l | grep pyqt5
ii  python3-pyqt5                              5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5
ii  python3-pyqt5-dbg                          5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5 (debug extensions)
ii  python3-pyqt5.qtmultimedia                 5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5's Multimedia module
ii  python3-pyqt5.qtquick                      5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for QtQuick module
ii  python3-pyqt5.qtwebkit                     5.10.1+dfsg-1ubuntu2                         amd64        Python 3 bindings for Qt5's WebKit module

```
```
yuhong@zyh:~/snap/firefox/common/Downloads$ dpkg -L python3-pyqt5.qtwebkit
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/PyQt5
/usr/lib/python3/dist-packages/PyQt5/QtWebKit.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/PyQt5/QtWebKit.pyi
/usr/lib/python3/dist-packages/PyQt5/QtWebKitWidgets.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/PyQt5/QtWebKitWidgets.pyi
/usr/share
/usr/share/doc
/usr/share/doc/python3-pyqt5.qtwebkit
/usr/share/doc/python3-pyqt5.qtwebkit/copyright
/usr/share/doc/python3-pyqt5.qtwebkit/changelog.Debian.gz

```

**Comment by yomun** [comment]
```
$ sudo gedit /usr/share/applications/youdao-dict.desktop

### Exec=youdao-dict %f
Exec=env PYTHONPATH=/usr/lib/python3/dist-packages youdao-dict %f
```

**Comment by Sophia409** [comment]
@yomun Hello，thank you for your reply.But I still met problems and I try `sudo -i` to chang my identity,but it still didn't work.Can you help me?
```
yuhong@zyh:~/snap/firefox/common/Downloads$ sudo gedit /usr/share/applications/youdao-dict.desktop
[sudo] yuhong 的密码： 

(gedit:4870): IBUS-WARNING **: 16:40:31.454: The owner of /home/yuhong/.config/ibus/bus is not root!

** (gedit:4870): WARNING **: 16:40:46.092: Set document metadata failed: 不支持设置属性 metadata::gedit-spell-language

** (gedit:4870): WARNING **: 16:40:46.093: Set document metadata failed: 不支持设置属性 metadata::gedit-encoding

```
```
yuhong@zyh:~/snap/firefox/common/Downloads$ sudo -i
root@zyh:~# sudo gedit /usr/share/applications/youdao-dict.desktop

** (gedit:5765): WARNING **: 16:49:07.382: Set document metadata failed: 不支持设置属性 metadata::gedit-spell-language

** (gedit:5765): WARNING **: 16:49:07.382: Set document metadata failed: 不支持设置属性 metadata::gedit-encoding

** (gedit:5765): WARNING **: 16:49:23.814: Set document metadata failed: 不支持设置属性 metadata::gedit-position
root@zyh:~#  gedit /usr/share/applications/youdao-dict.desktop

** (gedit:5794): WARNING **: 16:50:20.873: Set document metadata failed: 不支持设置属性 metadata::gedit-spell-language

** (gedit:5794): WARNING **: 16:50:20.873: Set document metadata failed: 不支持设置属性 metadata::gedit-encoding

** (gedit:5794): WARNING **: 16:50:24.148: Set document metadata failed: 不支持设置属性 metadata::gedit-position

```
![webwxgetmsgimg](https://user-images.githubusercontent.com/30619010/55143642-1adc0e80-517a-11e9-94a3-2fd8b4be38c2.jpg)

**Comment by yomun** [comment]
```
1) 检查有用 APT 安装上 PyQt5
----------------------------------------
$ apt search python3-pyqt5 | grep installed
python3-pyqt5/bionic,now 5.10.1+dfsg-1ubuntu2 amd64 [installed]
python3-pyqt5.qtmultimedia/bionic,now 5.10.1+dfsg-1ubuntu2 amd64 [installed]
python3-pyqt5.qtquick/bionic,now 5.10.1+dfsg-1ubuntu2 amd64 [installed]
python3-pyqt5.qtwebkit/bionic,now 5.10.1+dfsg-1ubuntu2 amd64 [installed]

确保 PyQt5 以上安装在 /usr/lib/python3/dist-packages/PyQt5

2) PIP3 上卸载 PyQt5 (目前最新是 5.12.1)
------------------------------------------------------
$ su
$ apt install python3-pip
$ pip3 list | grep PyQt5

如有列出 PyQt5, 
再查一查这个 PyQt5 是否安装在 /usr/local/lib/python3.6/dist-packages
$ pip3 show PyQt5

如是, 撤除 PyQt5 和 PyQt5-sip.
$ pip3 uninstall PyQt5 PyQt5-sip

3) 打开新的 terminal, 运行 (不用 $PYTHONPATH)
----------------------------------------------------------------
$ youdao-dict
```
