### ISSUE TITLE
ImportError: cannot import name 'QApplication

### ISSUE THREAD

**Issue by yuhanghai** [yomun/youdaodict_5.5#9]
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 31, in <module>
    from PyQt5.Qt import QApplication
ImportError: cannot import name 'QApplication' from 'PyQt5.Qt' (/usr/lib/python3/dist-packages/PyQt5/Qt.cpython-37m-x86_64-linux-gnu.so)

**Comment by yomun** [comment]
https://github.com/yomun/youdaodict_5.5/issues/5
